### ISSUE TITLE
Testar os Endpoints do Web Service

### ISSUE THREAD

**Issue by GolfettoGuilherme** [FabricaAppU9/EcoLocV2#2]

**Comment by GolfettoGuilherme** [comment]
[00:28, 17/9/2017] Jan ?: http://devjan.esy.es/ws_app/v1/doc/Create/usuarioDTOCreate.php                        
[00:28, 17/9/2017] Jan ?: http://devjan.esy.es/ws_app/v1/usuarioDTO.php?CHAVE=12345&CHAMADA=CRIARUSUARIODTO&NOME=GOLFETTO&LOGIN=GOLFETTO&SENHA=123456

INSERT INTO UsuarioDTO(id,nome,login,senha) VALUES('-1','GOLFETTO','GOLFETTO','123456'){"RETORNO":"SUCESSO", "ID":"34"}                        
[00:28, 17/9/2017] Jan ?: http://devjan.esy.es/ws_app/v1/usuarioDTO.php?CHAVE=12345&CHAMADA=GETUSUARIOSDTO&PARAM=

[{"id":"1","login":"","senha":"","nome":""},{"id":"2","login":"mile","senha":"1234","nome":"jamile "},{"id":"3","login":"JANAILSON ROCHA","senha":"JAN123","nome":"1234"},{"id":"4","login":"JANAILSON ROCHA DE SOUSA","senha":"JAN333","nome":"123456789"},{"id":"5","login":"jamile","senha":"mile","nome":"3221"},{"id":"6","login":"antonio carlos","senha":"TONY","nome":"1234"},{"id":"7","login":"JANAILSON ROCHA","senha":"JAN","nome":"1234"},{"id":"8","login":"JANAILSON ROCHA","senha":"sadf","nome":"sda"},{"id":"9","login":"tea","senha":"sda","nome":"sdgasd"},{"id":"34","login":"GOLFETTO","senha":"123456","nome":"GOLFETTO"},{"id":"10","login":"verme cinzento","senha":"verme","nome":"1234"},{"id":"11","login":"verme","senha":"1234","nome":"verme cinzento"},{"id":"12","login":"teste 01 01","senha":"888888","nome":" teste01 01"},{"id":"13","login":"test","senha":"test","nome":"teste"},{"id":"14","login":"f","senha":"f","nome":"f"},{"id":"15","login":"JGJG","senha":"GHJ","nome":"HGJ"},{"id":"16","login":"","senha":"","nome":"GDF"},{"id":"17","login":"h","senha":"h","nome":"h"},{"id":"18","login":"","senha":"","nome":"jan"},{"id":"19","login":"","senha":"","nome":"jan"},{"id":"20","login":"","senha":"","nome":"jan"},{"id":"21","login":"","senha":"","nome":"jan"},{"id":"22","login":"","senha":"","nome":"JANAILSON"},{"id":"23","login":"JAN","senha":"1234","nome":"JANAILSON"},{"id":"24","login":"","senha":"","nome":""},{"id":"25","login":"","senha":"","nome":"JANAILSON"},{"id":"26","login":"JAN","senha":"1234","nome":"JANAILSON ROCH"},{"id":"27","login":"JAN 123","senha":"fg","nome":"JANAILSON ROCHA"},{"id":"28","login":"","senha":"","nome":""},{"id":"29","login":"","senha":"","nome":""},{"id":"30","login":"","senha":"","nome":""},{"id":"31","login":"f","senha":"f","nome":"JANAILSON ROCHA"},{"id":"32","login":"","senha":"","nome":"JANAILSON ROCHA"},{"id":"33","login":"","senha":"","nome":""},{"id":"35","login":"GOLFETTO","senha":"123456","nome":"GOLFETTO"}]                        
[00:29, 17/9/2017] Jan ?: http://www.devjan.esy.es/ws_app/v1/usuarioDTO.php?CHAVE=12345&CHAMADA=UPDATEUSUARIODTO&NOME=GUILHERME+GOLFETTO&LOGIN=GOLFETTO&SENHA=123456&IDUSUARIO=35

UPDATE UsuarioDTO SET NOME = 'GUILHERME GOLFETTO', SENHA='123456', LOGIN='GOLFETTO' WHERE ID='35'{"RETORNO":"ATUALIZADO COM SUCESSO"}

**Comment by GolfettoGuilherme** [comment]
http://square.github.io/retrofit/

**Comment by Andre-VGoncalves** [comment]
http://www.mobimais.com.br/blog/retrofit-2-consumir-json-no-android/

**Comment by GolfettoGuilherme** [comment]
https://www.youtube.com/watch?v=nFIvV5_QTOE
